title: Majd Alsado
markdown: kramdown
url: ""
baseurl: ""

# for atom feed
author:
  name: Majd Alsado
  email: majd@alsado.ca

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
